version: '3.7'

services:
  db:
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_USER=nubuilder
      - MYSQL_PASSWORD=DB_PASSWORD
      - MYSQL_DATABASE=nubuilder
      - MYSQL_ROOT_PASSWORD=DB_ROOT_PASSWORD

  app:
    image: corna/nubuilder:4.5
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - nubuilder:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=nubuilder
      - DB_PASS=DB_PASSWORD
      - DB_NAME=nubuilder
      - GLOBE_USER=nubuilder
      - GLOBE_PASS=NUBUILDER_PASSWORD

  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - nubuilder:/var/www/html:ro
      - /path/to/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  db:
  nubuilder:
