version: '3.7'

services:


  app:
    image: nubuildertest:v5
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_USER=nubuilder
      - DB_PASS=DB_PASSWORD
      - DB_NAME=nubuilder
      - GLOBE_USER=nubuilder
      - GLOBE_PASS=NUBUILDER_PASSWORD
      #- NUBUILDER_INSTALL_DIR=/var/www/html/ # This is the default install dir and is normally set as /var/www/html/. Uncomment and change as desired to run multiple webservers not only installed to /var/www/html/. 
    volumes:
      - nubuilder:/var/www/nubuilder/ # Change this accordingly to NUBUILDER_INSTALL_DIR if you want to keep the downloaded nubuilder instance
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - nubuilder:/var/www/nubuilder:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  
  nubuilder:
